#!/usr/bin/env python3
"""
HTML to C Header Converter
Converts dashboard.html to dashboard.h for embedding in ESP32 firmware
"""

import sys
import os

def html_to_c_header(html_file, header_file):
    """Convert HTML file to C header with string constant"""
    
    # Read HTML file
    try:
        with open(html_file, 'r', encoding='utf-8') as f:
            html_content = f.read()
    except Exception as e:
        print(f"Error reading {html_file}: {e}")
        sys.exit(1)
    
    # Minify HTML (optional - remove for readability)
    # For now, keep it readable but you can add minification
    
    # Escape special characters for C string
    html_escaped = html_content.replace('\\', '\\\\')  # Backslash
    html_escaped = html_escaped.replace('"', '\\"')     # Double quote
    html_escaped = html_escaped.replace('\n', '\\n')    # Newline
    html_escaped = html_escaped.replace('\r', '')       # Remove carriage return
    
    # Generate C header content
    header_content = f"""#ifndef DASHBOARD_H
#define DASHBOARD_H

// Auto-generated from dashboard.html
// DO NOT EDIT THIS FILE MANUALLY - Edit dashboard.html instead

static const char* dashboard_html = 
"{html_escaped}";

#endif // DASHBOARD_H
"""
    
    # Write header file
    try:
        with open(header_file, 'w', encoding='utf-8') as f:
            f.write(header_content)
        print(f"✅ Successfully converted {html_file} to {header_file}")
        print(f"   HTML size: {len(html_content)} bytes")
        print(f"   Header size: {len(header_content)} bytes")
    except Exception as e:
        print(f"Error writing {header_file}: {e}")
        sys.exit(1)

if __name__ == "__main__":
    # Get script directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    # Input and output files
    html_file = os.path.join(script_dir, "dashboard.html")
    header_file = os.path.join(script_dir, "dashboard.h")
    
    print("=" * 60)
    print("HTML to C Header Converter")
    print("=" * 60)
    
    html_to_c_header(html_file, header_file)
    
    print("=" * 60)
    print("Done! Include 'dashboard.h' in your web_server.c")
    print("=" * 60)
